package pro.deta.orion.provisioning;

public enum ProvisioningFailure {
    CONNECTION,
    HOST_IDENTITY,
    AUTHENTICATION,
    REMOTE_PLATFORM,
    RUNTIME_UNAVAILABLE,
    TRANSFER,
    INTEGRITY,
    ACTIVATION,
    LAUNCH,
    UNSAFE_IDENTITY,
    MALFORMED_IDENTITY,
    UNCERTAIN_IDENTITY,
    SIGNAL_PRIVILEGE,
    TERMINATION_TIMEOUT,
    STARTUP_TIMEOUT,
    RETRIES_EXHAUSTED,
    REMOTE_COMMAND,
    TIMEOUT
}
