<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>pro.deta.orion.tests</groupId>
        <artifactId>tests</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>git-engine-orion-adapters</artifactId>

    <dependencies>
        <dependency>
            <groupId>pro.deta.orion.net</groupId>
            <artifactId>http-core</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>pro.deta.orion.tests</groupId>
            <artifactId>git-engine-test-support</artifactId>
        </dependency>
        <dependency>
            <groupId>pro.deta.orion.tests</groupId>
            <artifactId>test-duration-recorder</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <junit.jupiter.execution.parallel.enabled>
                            true
                        </junit.jupiter.execution.parallel.enabled>
                        <junit.jupiter.execution.parallel.config.strategy>
                            fixed
                        </junit.jupiter.execution.parallel.config.strategy>
                        <junit.jupiter.execution.parallel.config.fixed.parallelism>
                            4
                        </junit.jupiter.execution.parallel.config.fixed.parallelism>
                        <junit.jupiter.execution.parallel.config.fixed.max-pool-size>
                            4
                        </junit.jupiter.execution.parallel.config.fixed.max-pool-size>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
