<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>pro.deta.orion</groupId>
    <artifactId>bom</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <properties>
        <revision>1.0-SNAPSHOT</revision>
        <netty.version>4.2.1.Final</netty.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-buffer</artifactId>
                <version>${netty.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-transport</artifactId>
                <version>${netty.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>${netty.version}</version>
            </dependency>

            <dependency>
                <groupId>pro.deta.orion</groupId>
                <artifactId>session-host-native</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion</groupId>
                <artifactId>agent-protocol</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion</groupId>
                <artifactId>agent-session-server</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.core</groupId>
                <artifactId>schema</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.core.ref</groupId>
                <artifactId>reference</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.core</groupId>
                <artifactId>acl</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.connectors</groupId>
                <artifactId>acl-storage</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.connectors</groupId>
                <artifactId>configuration-location</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.core</groupId>
                <artifactId>authorization</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.core</groupId>
                <artifactId>command</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.core</groupId>
                <artifactId>bootstrap</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.core</groupId>
                <artifactId>common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.core</groupId>
                <artifactId>common-runtime</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.git</groupId>
                <artifactId>git-parser</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.git</groupId>
                <artifactId>git-native-storage</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.git</groupId>
                <artifactId>git-native-proxy</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.git</groupId>
                <artifactId>git-client</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.connectors</groupId>
                <artifactId>bc</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.connectors</groupId>
                <artifactId>sshd-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.core</groupId>
                <artifactId>key-material</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.tests</groupId>
                <artifactId>git-engine-test-support</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.tests</groupId>
                <artifactId>git-engine-interoperability-matrix</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.tests</groupId>
                <artifactId>integration-test-support</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.core</groupId>
                <artifactId>communication</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.net</groupId>
                <artifactId>frontend-ui</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.net</groupId>
                <artifactId>net-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.net</groupId>
                <artifactId>git-transport</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.tests</groupId>
                <artifactId>integration-test</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.tests</groupId>
                <artifactId>test-support</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.tests</groupId>
                <artifactId>test-duration-recorder</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.integration</groupId>
                <artifactId>cloudflare-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.net</groupId>
                <artifactId>http-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.net</groupId>
                <artifactId>transport</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pro.deta.orion.git</groupId>
                <artifactId>git</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
